name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
    - name: chmod excutable for gradlew file
      run: chmod +x ./gradlew    
    - name: Build with Gradle Wrapper
      run: ./gradlew build
  #  - name: Check
  #    run: ls -l build/libs/
  #deploy:  
  #  permissions:
  #    contents: write
  #  needs: build
  #  runs-on: ubuntu-latest
  #  steps:
  #  - name: Check
  #    run: ls -l build/libs/
    - name: SCP artifact file to VM
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}  # GCP VM의 IP 주소
        username: ${{ secrets.USERNAME }}  # SSH 계정 이름
        key: ${{ secrets.GCP_DEMO_PRIVATE_KEY }}  # SSH 개인 키
        port: ${{ secrets.PORT }}  # SSH Port
        source: "./build/libs/springaj-0.0.1-SNAPSHOT.jar"  # 빌드된 JAR 파일 경로
        target: "/home/aedorablee_gmail_com/artifact"  # GCP VM에 전송할 디렉토리 경로
        strip_components: 2
    - name: SSH into GCP VM and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}  # GCP VM의 IP 주소
        username: ${{ secrets.USERNAME }} # SSH 계정 이름
        key: ${{ secrets.GCP_DEMO_PRIVATE_KEY }}  # SSH 개인 키
        port: ${{ secrets.PORT }}  # SSH Port
        script: |
          cd /home/aedorablee_gmail_com/artifact/build/libs/
          chmod +x ./script/app_stop.sh
          sudo ./script/app_stop.sh
          echo "service stop"
          sleep 10
          mv springaj-0.0.1-SNAPSHOT.jar app.jar
          chmod +x ./script/app_start.sh
          sudo ./script/app_start.sh
          sleep 10
          chmod +x ./script/app_status_check.sh
          sudo ./script/app_status_check.sh
          echo "service check"
          
        #script: |
        #  cd /home/aedorablee_gmail_com/artifact/build/libs/  # 전송된 JAR 파일이 위치한 디렉토리로 이동
        #  sudo systemctl stop java  # 서비스 중단
        #  mv springaj-0.0.1-SNAPSHOT.jar app.jar  # JAR 파일 이름 변경
        #  sudo systemctl start java  # 서비스 시작
